### ISSUE TITLE
Bootloop after patching the spoofify.

### ISSUE THREAD

**Issue by lvpha** [Otus9051/spoof11#1]
Hey, 
First, I want to thank you for the simplified post. I performed the above steps on a Windows machine. I used SDK dev tools for ADB and Java dev tool to perform the Java and Jar commands to pack the dex into a jar file.

All went smooth, no warnings, no errors. Patched the spoofify and boom. phone doesn't boot. Could it be that Magisk failed to set the chmod 755 on the new services.jar?

**Comment by Otus9051** [comment]
Windows...
try with a linux vm eh? Specially the dexpatching, or send over your /system/framework/services.jar either here or in my discord Otus9051#5971. Also if you have /proc/last_kmsg or /sys/fs/pstore/, send it as a zip.

also holy shit people use this?

**Comment by Otus9051** [comment]
Closing issue due to no response from author
